version: "3.2"

services:
  mysql:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "$PWD/mysql/data:/var/lib/mysql"
      - "$PWD/mysql/conf:/etc/mysql/conf.d/"
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:latest
    environment:
      MODE: standalone
#    volumes:
#      - "$PWD/nacos/standalone-logs/:/home/nacos/logs"
#      - "$PWD/nacos/conf/application.properties:/home/nacos/conf/application.properties"
    ports:
      - "8848:8848"
    restart: always
    depends_on:
      - mysql
#    network_mode: host
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - "$PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/nginx/conf/conf.d:/etc/nginx/conf.d"
      - "$PWD/nginx/html:/usr/share/nginx/html"
      - "$PWD/nginx/logs:/var/log/nginx"
    ports:
      - "80:80"
    restart: always
#    privileged: true
    depends_on:
      - nacos1
  gateway:
    build: ./gateway
    ports:
      - "10000:10000"
    depends_on:
      - nacos1
#      - nginx
  icc-menber:
    build: ./icc-menber
    depends_on:
      - nacos1
      - nginx
  icc-product:
    build: ./icc-product
    depends_on:
      - nacos1
      - nginx
  icc-order:
    build: ./icc-order
    depends_on:
      - nacos1
      - nginx
  icc-ware:
    build: ./icc-ware
    depends_on:
      - nacos1
      - nginx
  icc-coupon:
    build: ./icc-coupon
    depends_on:
      - nacos1
      - nginx
