### ----本地配置----

server:
  port: 10000 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: www.icc.com:80 # nacos地址
      discovery:
        namespace: 50aa700e-16d1-4614-bb4f-fc21bf5de3c5
    gateway:
      routes: # 网关路由配置
        - id: icc-menber # 路由id，自定义，只要唯一即可
          # uri: http://localhost:9001 # 路由的目标地址 http就是固定地址
          uri: lb://icc-menber # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/menber/** # 这个是按照路径匹配，只要以/user/开头就符合要求

        - id: icc-product # 路由id，自定义，只要唯一即可
          # uri: http://localhost:9001 # 路由的目标地址 http就是固定地址
          uri: lb://icc-product # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/product/** # 这个是按照路径匹配，只要以/user/开头就符合要求

        - id: icc-ware # 路由id，自定义，只要唯一即可
          # uri: http://localhost:9001 # 路由的目标地址 http就是固定地址
          uri: lb://icc-ware # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/ware/** # 这个是按照路径匹配，只要以/user/开头就符合要求

        - id: icc-order # 路由id，自定义，只要唯一即可
          # uri: http://localhost:9001 # 路由的目标地址 http就是固定地址
          uri: lb://icc-order # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/order/** # 这个是按照路径匹配，只要以/user/开头就符合要求

        - id: icc-coupon # 路由id，自定义，只要唯一即可
          # uri: http://localhost:9001 # 路由的目标地址 http就是固定地址
          uri: lb://icc-coupon # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/coupon/** # 这个是按照路径匹配，只要以/user/开头就符合要求