### -----------------------本地配置----------------------------

## -----------------------ribbon负载均衡-----------------------
# 针对要访问的各个服务设置负载均衡策略
# NacosRule：
# 1、先访问同一个集群中的服务实例；如果同集群中没有该服务实例则访问其他集群的，且报警提示；
# 2、确定服务列表；
# 3、在列表中采用随机访问策略
icc-product:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
icc-ware:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
icc-order:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
icc-coupon:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
# 针对要访问的各个服务设置负载均衡饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients:
      - icc-product
      - icc-ware
      - icc-order
      - icc-coupon

## -----------------------feign远程调用-----------------------
feign:
  client:
    config:
      default: # default全局的配置；或者# 针对某个微服务的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数