### -----------------------本地配置----------------------------

## -----------------------ribbon负载均衡-----------------------
# 针对要访问的各个服务设置负载均衡策略
# NacosRule：
# 1、先访问同一个集群中的服务实例；如果同集群中没有该服务实例则访问其他集群的，且报警提示；
# 2、确定服务列表；
# 3、在列表中采用随机访问策略
icc-product:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
icc-ware:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
icc-order:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
icc-coupon:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
# 针对要访问的各个服务设置负载均衡饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients:
      - icc-product
      - icc-ware
      - icc-order
      - icc-coupon

## -----------------------feign远程调用-----------------------
feign:
  client:
    config:
      default: # default全局的配置；或者# 针对某个微服务的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
  sentinel:
    enabled: true # 开启feign对sentinel的支持

## -----------------------rabbitmq消息队列-----------------------
spring:
  rabbitmq:
    host: localhost #主机名
    port: 5672 #端口
    username: guest #用户名
    password: guest #密码
    virtual-host: / #虚拟主机
    listener:
      direct:
        prefetch: 1 # 每次只能获取一条消息，处理完才能获取下一个消息

## -----------------------sentinel流量控制-----------------------
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090

## -----------------------mysql数据库-----------------------
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/heima?useUnicode=true & characterEncoding=utf-8 & useSSL=false & serverTimezone=GMT%2B8 & allowPublicKeyRetrieval=true
    username: root
    password: 123456

## -----------------------mybatis-plus配置-----------------------
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.iccmenber.demo03.pojo

## -----------------------seata配置-----------------------
seata:
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    type: nacos # 注册中心类型 nacos
    nacos:
      server-addr: 192.168.145.101:80 # nacos地址
      namespace: "" # namespace，默认为空
      group: DEFAULT_GROUP # 分组，默认是DEFAULT_GROUP
      application: seata-tc-server # seata服务名称
      username: nacos
      password: nacos
  tx-service-group: seata-demo # 事务组名称
  service:
    vgroup-mapping: # 事务组与cluster的映射关系
      seata-demo: SH
  data-source-proxy-mode: XA  # AT\TCC\Saga @


#logging:
#  level:
#    com.example: debug
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS

